options:
  logging: CLOUD_LOGGING_ONLY


steps:

steps:
-name: 'gcr.io/cloud-builders/docker'
 args:  docker build -t  asia-south1-docker.pkg.dev/prj-hotelogic-poc-01-22106/docker-task/prajesh-docker:v1 .
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
    
      gcloud auth configure-docker asia-south1-docker.pkg.dev
      gcloud auth list
      gcloud config list
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south1-docker.pkg.dev/prj-hotelogic-poc-01-22106/docker-task/prajesh-docker:v1']

