steps:
  - id: test-builds-successfully
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    dir: basic-config
    entrypoint: /bin/bash
    args: 
      - '-c'
      - |
        gcloud builds submit --config cloudbuild.yaml

  - id: cleanup
    name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: /bin/bash
    args:
      - '-c'
      - |
        gcloud compute instances delete my-vm-name --zone asia-south1-a
        gcloud artifacts docker images delete asia-south1-docker.pkg.dev/prj-common-srv-single-01/my-docker-repo/myimage
